apiVersion: apps/v1
kind: Deployment
metadata:
  name: lr-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: lr-backend
  template:
    metadata:
      labels:
        app: lr-backend
    spec:
      imagePullSecrets:
              {{- toYaml .Values.backend.imagePullSecrets | nindent 8 }}
      containers:
        - name: lr-backend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lr-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lr-db-credentials
                  key: password