apiVersion: apps/v1
kind: Deployment
metadata:
  name: lr-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: lr-frontend
  template:
    metadata:
      labels:
        app: lr-frontend
    spec:
      nodeSelector:
        project: lr
      imagePullSecrets:
              {{- toYaml .Values.frontend.imagePullSecrets | nindent 8 }}
      containers:
        - name: lr-backend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.service.port }}