global:
  imageRegistry: ""   # from CI
  imageTag: ""        # from CI

backend:
  replicaCount: 1
  image:
    repository: ""
    tag: ""
  service:
    port: 8080
  imagePullSecrets:
    - name: gitlab-registry

frontend:
  replicaCount: 1
  image:
    repository: ""
    tag: ""
  service:
    port: 80
  imagePullSecrets:
    - name: gitlab-registry