global:
  imageRegistry: ""   # from CI
  imageTag: ""        # from CI

backend:
  replicaCount: 1
  image:
    repository: ""
    tag: ""
  service:
    port: 8080
  imagePullSecrets:
    - name: gitlab-registry
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://lr-postgres:5432/lebens_rhythmus

postgres:
  db: lebens_rhythmus
  storage: 10Gi

frontend:
  replicaCount: 1
  image:
    repository: ""
    tag: ""
  service:
    port: 80
  imagePullSecrets:
    - name: gitlab-registry